// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package forms.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Forms module
	public static void addOptions(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Forms.AddOptions").withParams(params).execute(context);
	}
	public static forms.proxies.AdminDashboard adminDashboardCount(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Forms.AdminDashboardCount").withParams(params).execute(context);
		return result == null ? null : forms.proxies.AdminDashboard.initialize(context, result);
	}
	public static void backToHome(IContext context, forms.proxies.Response _response)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		Core.microflowCall("Forms.BackToHome").withParams(params).execute(context);
	}
	public static administration.proxies.Account findCurrentAccount(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Forms.FindCurrentAccount").withParams(params).execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, result);
	}
	public static void newResponse(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Forms.NewResponse").withParams(params).execute(context);
	}
	public static void saveOpions(IContext context, forms.proxies.Response _response)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		Core.microflowCall("Forms.SaveOpions").withParams(params).execute(context);
	}
	public static void submitForm(IContext context, forms.proxies.Response _response)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		Core.microflowCall("Forms.SubmitForm").withParams(params).execute(context);
	}
}
