// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package appswitchermodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the AppSwitcherModule module
	public static java.lang.String dS_CustomAuthentication(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.String) Core.microflowCall("AppSwitcherModule.DS_CustomAuthentication").withParams(params).execute(context);
	}
	public static appswitchermodule.proxies.CustomToken parseAuthorization(IContext context, java.lang.String _customAuthToken)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("customAuthToken", _customAuthToken);
		IMendixObject result = (IMendixObject)Core.microflowCall("AppSwitcherModule.ParseAuthorization").withParams(params).execute(context);
		return result == null ? null : appswitchermodule.proxies.CustomToken.initialize(context, result);
	}
}
