// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package forms.proxies;

public class AdminDashboard
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject adminDashboardMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Forms.AdminDashboard";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ResponsesCount("ResponsesCount"),
		FinishRatio("FinishRatio"),
		AverageCompletionTime("AverageCompletionTime");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AdminDashboard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AdminDashboard(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject adminDashboardMendixObject)
	{
		if (adminDashboardMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, adminDashboardMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.adminDashboardMendixObject = adminDashboardMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AdminDashboard.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static forms.proxies.AdminDashboard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return forms.proxies.AdminDashboard.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static forms.proxies.AdminDashboard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new forms.proxies.AdminDashboard(context, mendixObject);
	}

	public static forms.proxies.AdminDashboard load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return forms.proxies.AdminDashboard.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ResponsesCount
	 */
	public final java.lang.Integer getResponsesCount()
	{
		return getResponsesCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponsesCount
	 */
	public final java.lang.Integer getResponsesCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ResponsesCount.toString());
	}

	/**
	 * Set value of ResponsesCount
	 * @param responsescount
	 */
	public final void setResponsesCount(java.lang.Integer responsescount)
	{
		setResponsesCount(getContext(), responsescount);
	}

	/**
	 * Set value of ResponsesCount
	 * @param context
	 * @param responsescount
	 */
	public final void setResponsesCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer responsescount)
	{
		getMendixObject().setValue(context, MemberNames.ResponsesCount.toString(), responsescount);
	}

	/**
	 * @return value of FinishRatio
	 */
	public final java.math.BigDecimal getFinishRatio()
	{
		return getFinishRatio(getContext());
	}

	/**
	 * @param context
	 * @return value of FinishRatio
	 */
	public final java.math.BigDecimal getFinishRatio(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.FinishRatio.toString());
	}

	/**
	 * Set value of FinishRatio
	 * @param finishratio
	 */
	public final void setFinishRatio(java.math.BigDecimal finishratio)
	{
		setFinishRatio(getContext(), finishratio);
	}

	/**
	 * Set value of FinishRatio
	 * @param context
	 * @param finishratio
	 */
	public final void setFinishRatio(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal finishratio)
	{
		getMendixObject().setValue(context, MemberNames.FinishRatio.toString(), finishratio);
	}

	/**
	 * @return value of AverageCompletionTime
	 */
	public final java.lang.String getAverageCompletionTime()
	{
		return getAverageCompletionTime(getContext());
	}

	/**
	 * @param context
	 * @return value of AverageCompletionTime
	 */
	public final java.lang.String getAverageCompletionTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AverageCompletionTime.toString());
	}

	/**
	 * Set value of AverageCompletionTime
	 * @param averagecompletiontime
	 */
	public final void setAverageCompletionTime(java.lang.String averagecompletiontime)
	{
		setAverageCompletionTime(getContext(), averagecompletiontime);
	}

	/**
	 * Set value of AverageCompletionTime
	 * @param context
	 * @param averagecompletiontime
	 */
	public final void setAverageCompletionTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String averagecompletiontime)
	{
		getMendixObject().setValue(context, MemberNames.AverageCompletionTime.toString(), averagecompletiontime);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return adminDashboardMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final forms.proxies.AdminDashboard that = (forms.proxies.AdminDashboard) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
